/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./app/views/**/*.{html,erb}",
    "./app/frontend/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        error: "#ba1a1a",
        "surface-tint": "#406182",
        "on-tertiary": "#ffffff",
        "secondary-fixed-dim": "#59dad1",
        "on-error-container": "#93000a",
        "on-tertiary-container": "#839493",
        "on-surface": "#191c1e",
        "on-secondary-container": "#006f69",
        "surface-variant": "#e0e3e5",
        "inverse-surface": "#2d3133",
        secondary: "#006a65",
        "on-background": "#191c1e",
        "surface-dim": "#d8dadc",
        tertiary: "#071717",
        "on-surface-variant": "#42474d",
        "on-tertiary-fixed-variant": "#3a4a49",
        "surface-container-lowest": "#ffffff",
        "on-error": "#ffffff",
        "surface-container-high": "#e6e8ea",
        "surface-container": "#eceef0",
        "secondary-container": "#76f3ea",
        "tertiary-container": "#1c2c2c",
        "error-container": "#ffdad6",
        outline: "#73777e",
        "on-primary-fixed-variant": "#274969",
        "on-secondary-fixed": "#00201e",
        "inverse-primary": "#a8caef",
        "surface-bright": "#f7f9fb",
        "on-primary": "#ffffff",
        "surface-container-highest": "#e0e3e5",
        surface: "#f7f9fb",
        "tertiary-fixed-dim": "#b8cac9",
        "primary-fixed-dim": "#a8caef",
        primary: "#001629",
        background: "#f7f9fb",
        "on-tertiary-fixed": "#0e1e1e",
        "inverse-on-surface": "#eff1f3",
        "on-secondary-fixed-variant": "#00504c",
        "primary-container": "#002b49",
        "surface-container-low": "#f2f4f6",
        "primary-fixed": "#cfe5ff",
        "secondary-fixed": "#79f6ed",
        "tertiary-fixed": "#d4e6e5",
        "on-secondary": "#ffffff",
        "on-primary-container": "#7293b6",
        "outline-variant": "#c3c7ce",
        "on-primary-fixed": "#001d34",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        base: "8px",
        "stack-md": "24px",
        "section-padding-desktop": "120px",
        "grid-gutter": "24px",
        "container-max-width": "1280px",
        "stack-sm": "12px",
        "stack-lg": "48px",
        "container-margin": "24px",
      },
      fontFamily: {
        "display-lg": ["Manrope", "sans-serif"],
        "label-md": ["Manrope", "sans-serif"],
        "body-md": ["Manrope", "sans-serif"],
        "body-lg": ["Manrope", "sans-serif"],
        "headline-md": ["Manrope", "sans-serif"],
        "headline-sm": ["Manrope", "sans-serif"],
        "headline-lg": ["Manrope", "sans-serif"],
      },
      fontSize: {
        "display-lg": ["64px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "800" }],
        "label-md": ["14px", { lineHeight: "1", letterSpacing: "0.05em", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "headline-md": ["32px", { lineHeight: "1.3", fontWeight: "700" }],
        "headline-sm": ["24px", { lineHeight: "1.4", fontWeight: "600" }],
        "headline-lg": ["48px", { lineHeight: "1.2", letterSpacing: "-0.01em", fontWeight: "700" }],
        "body-sm": ["14px", { lineHeight: "1.6", fontWeight: "400" }],
      },
      animation: {
        "fade-in": "fadeIn 0.7s ease-out",
        bounce: "bounce 1s infinite",
      },
      keyframes: {
        fadeIn: {
          "0%": { opacity: "0", transform: "translateY(10px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        bounce: {
          "0%, 100%": { transform: "translateY(0)" },
          "50%": { transform: "translateY(-10px)" },
        },
      },
    },
  },
  plugins: [],
};
